apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: shared-pvc

