apiVersion: batch/v1
kind: Job
metadata:
  name: content-copy-job
spec:
  template:
    spec:
      containers:
      - name: content-copier
        image: alpine
        command: ['sh', '-c', 'echo "<h1>Hello from Apache Server!</h1>" > /data/index.html']
        volumeMounts:
        - name: content-volume
          mountPath: /data
      restartPolicy: OnFailure
      volumes:
      - name: content-volume
        persistentVolumeClaim:
          claimName: shared-pvc

